#  DATOS DE TRAFICO 

- Eliminar distritos que no utilizo
- Eliminar datos no validos

In [1]:
import pandas as pd

df_datos = pd.read_csv("datos/CONT_METEO_REDUCIDO_2021_2024.csv")

df_datos.drop(columns='Unnamed: 0', inplace=True)

df_datos

,ESTACION,DISTRITO,FECHA_HORA,NO,NO2,NOx,PM10,PM2_5,TEMP,HUM_REL,PRECIPITACION,PRES_BARIOMETRICA,RAD_SOL,DIR_VIENT,VEL_VIENT
0,8,3,2021-01-01 01:00:00,4.0,23.0,28.0,8.0,7.0,3.3,92.0,NaN,NaN,NaN,NaN,NaN
1,8,3,2021-01-01 02:00:00,6.0,36.0,46.0,12.0,10.0,3.2,89.0,NaN,NaN,NaN,NaN,NaN
2,8,3,2021-01-01 03:00:00,2.0,19.0,22.0,5.0,4.0,3.8,83.0,NaN,NaN,NaN,NaN,NaN
3,8,3,2021-01-01 04:00:00,1.0,12.0,13.0,5.0,4.0,4.0,83.0,NaN,NaN,NaN,NaN,NaN
4,8,3,2021-01-01 05:00:00,1.0,12.0,13.0,1.0,1.0,3.9,81.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
338953,60,8,2023-12-31 20:00:00,5.0,30.0,37.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
338954,60,8,2023-12-31 21:00:00,6.0,35.0,44.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
338955,60,8,2023-12-31 22:00:00,4.0,37.0,44.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
338956,60,8,2023-12-31 23:00:00,2.0,20.0,23.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
338957,60,8,2023-12-31 00:00:00,2.0,15.0,19.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
distritos_lista = df_datos['DISTRITO'].unique()
distritos_lista.sort()
distritos_lista

array([ 2,  3,  4,  5,  6,  8,  9, 11, 12, 14, 16, 18, 21])

In [3]:
# Lectura datos trafico

df = pd.read_csv("datos/trafico2021_2023.csv")

df

           Unnamed: 0    id                fecha tipo_elem  intensidad error
0                   0  1001  2021-01-01 00:00:00       M30         144     N
1                   1  1001  2021-01-01 00:15:00       M30          84     N
2                   2  1001  2021-01-01 00:30:00       M30         108     N
3                   3  1001  2021-01-01 00:45:00       M30         792     N
4                   4  1001  2021-01-01 01:00:00       M30        1704     N
...               ...   ...                  ...       ...         ...   ...
424107274   142128614  4744  2023-12-08 05:15:00       URB          51     N
424107275   142128615  4744  2023-12-08 05:30:00       URB          64     N
424107276   142128616  4744  2023-12-08 05:45:00       URB          48     N
424107277   142128617  4744  2023-12-08 06:00:00       URB          60     N
424107278   142128618  4744  2023-12-08 06:15:00       URB          48     N

[424107279 rows x 6 columns]

Para poder eliminar los distritos, primero debo añadirselo por id, a partir del df de ubicaciones

- PRIMERO VOY A LEER LOS IDS DE LAS UBICACIONES DONDE EL DISTRITO ESTÁ EN EL LISTADO ANTERIOR
- DESPUES OBTENER UNA LISTA DE IDS
- CON ESA LISTA DE IDS ELIMINAR LOS QUE NO ESTEN EN EL DF TRAFICO Y SOBREESCRIBIRLO

### UBICACIONES

In [4]:
df_ubicaciones = pd.read_csv("datos/ubicaciones_sensores_trafico.csv")
df_ubicaciones

,Unnamed: 0,tipo_elem,distrito,id,cod_cent,nombre,utm_x,utm_y,longitud,latitud
0,0,URB,4.0,3840,01001,Jose Ortega y Gasset E-O - Pº Castellana-Serrano,441615.343346657,4475767.9421385,-3.6883232754856,40.4305018691825
1,1,URB,4.0,3841,01002,Jose Ortega y Gasset O-E - Serrano-Pº Castellana,441705.882339595,4475769.68733175,-3.68725610305613,40.4305239406404
2,2,URB,1.0,3842,01003,Pº Recoletos N-S - Almirante-Prim,441319.371258338,4474841.15423716,-3.6917268449043,40.4221320929972
3,3,URB,4.0,3843,01004,Pº Recoletos S-N - Pl. Cibeles- Recoletos,441301.63298559,4474763.7275141,-3.69192878230734,40.4214333442836
4,4,URB,4.0,3844,01005,(AFOROS) Pº Castellana S-N - Eduardo Dato - P...,441605.765071902,4476132.13924728,-3.68846965033102,40.4337820578943
...,...,...,...,...,...,...,...,...,...,...
5423,5423,URB,16.0,11235,72406,Av. Secundino Zuazo - César Cort Boti-Gta. Jos...,448.388.147.010.537,448.286.747.130.414,-360.905.755.542.047,404.949.062.864.003
5424,5424,URB,16.0,11276,72407,Av. Manuel Fraga Iribarne (CARRIL BUS) - AV. M...,44.843.325.332.997,448.251.275.311.267,-360.849.642.913.409,404.917.136.031.255
5425,5425,URB,16.0,11277,72408,Av. Manuel Fraga Iribarne (CARRIL BUS) - Jordi...,448.436.665.701.945,448.282.732.568.793,-360.848.176.299.328,404.945.476.496.166
5426,5426,URB,16.0,11279,72409,Secundino Zuazo (CARRIL BUS) - Josefina Aldeco...,447.824.682.462.605,448.294.459.287.868,-361.571.283.696.763,404.955.658.049.048
5427,5427,URB,16.0,11278,72410,Secundino Zuazo (CARRIL BUS) - Fina de Calderó...,447.748.942.805.197,448.294.078.306.391,-361.660.626.563.366,40.495.526.719.101

In [5]:
df_ubicaciones = df_ubicaciones[df_ubicaciones['distrito'].isin(distritos_lista)]
df_ubicaciones

,Unnamed: 0,tipo_elem,distrito,id,cod_cent,nombre,utm_x,utm_y,longitud,latitud
0,0,URB,4.0,3840,01001,Jose Ortega y Gasset E-O - Pº Castellana-Serrano,441615.343346657,4475767.9421385,-3.6883232754856,40.4305018691825
1,1,URB,4.0,3841,01002,Jose Ortega y Gasset O-E - Serrano-Pº Castellana,441705.882339595,4475769.68733175,-3.68725610305613,40.4305239406404
3,3,URB,4.0,3843,01004,Pº Recoletos S-N - Pl. Cibeles- Recoletos,441301.63298559,4474763.7275141,-3.69192878230734,40.4214333442836
4,4,URB,4.0,3844,01005,(AFOROS) Pº Castellana S-N - Eduardo Dato - P...,441605.765071902,4476132.13924728,-3.68846965033102,40.4337820578943
5,5,URB,4.0,3845,01006,Pº Recoletos S-N - Villanueva-Jorge Juan,441382.968851413,4474993.8634694,-3.69099128548591,40.4235122547331
...,...,...,...,...,...,...,...,...,...,...
5423,5423,URB,16.0,11235,72406,Av. Secundino Zuazo - César Cort Boti-Gta. Jos...,448.388.147.010.537,448.286.747.130.414,-360.905.755.542.047,404.949.062.864.003
5424,5424,URB,16.0,11276,72407,Av. Manuel Fraga Iribarne (CARRIL BUS) - AV. M...,44.843.325.332.997,448.251.275.311.267,-360.849.642.913.409,404.917.136.031.255
5425,5425,URB,16.0,11277,72408,Av. Manuel Fraga Iribarne (CARRIL BUS) - Jordi...,448.436.665.701.945,448.282.732.568.793,-360.848.176.299.328,404.945.476.496.166
5426,5426,URB,16.0,11279,72409,Secundino Zuazo (CARRIL BUS) - Josefina Aldeco...,447.824.682.462.605,448.294.459.287.868,-361.571.283.696.763,404.955.658.049.048
5427,5427,URB,16.0,11278,72410,Secundino Zuazo (CARRIL BUS) - Fina de Calderó...,447.748.942.805.197,448.294.078.306.391,-361.660.626.563.366,40.495.526.719.101

De 5500 Paso a 3600

In [7]:
ids_lista = df_ubicaciones['id'].unique()
ids_lista.sort()
len(ids_lista)

3260

### Eliminar ids no presentes en el df trafico

In [8]:
df = df[df['id'].isin(ids_lista)]
df

           Unnamed: 0    id                fecha tipo_elem  intensidad error
11892           11892  1009  2021-01-01 00:00:00       M30         180     N
11893           11893  1009  2021-01-01 00:15:00       M30         108     N
11894           11894  1009  2021-01-01 00:30:00       M30         108     N
11895           11895  1009  2021-01-01 00:45:00       M30         672     N
11896           11896  1009  2021-01-01 01:00:00       M30        1452     N
...               ...   ...                  ...       ...         ...   ...
424091712   142113052  4738  2023-12-31 22:45:00       URB          20     N
424091713   142113053  4738  2023-12-31 23:00:00       URB          30     N
424091714   142113054  4738  2023-12-31 23:15:00       URB          20     N
424091715   142113055  4738  2023-12-31 23:30:00       URB          22     N
424091716   142113056  4738  2023-12-31 23:45:00       URB          12     N

[276996275 rows x 6 columns]

In [9]:
len(df['id'].unique())

3135

De 424.107.279 filas paso a 276.996.275

In [10]:
# Sobreescribir

df = df.drop('Unnamed: 0', axis=1)

df.to_csv("datos/trafico2021_2023.csv")

De 18 GB paso a 12 GB