# Resumen

## Datos Contaminación y Meteo

Tengo los datos de las estaciones y distritos que mas mediciones tienen.

He eliminado los contaminantes poco importantes

In [5]:
import pandas as pd

df_cont_meteo = pd.read_csv("datos/CONT_METEO_REDUCIDO_2021_2024.csv")

df_cont_meteo

,Unnamed: 0,ESTACION,DISTRITO,FECHA_HORA,NO,NO2,NOx,PM10,PM2_5,TEMP,HUM_REL,PRECIPITACION,PRES_BARIOMETRICA,RAD_SOL,DIR_VIENT,VEL_VIENT
0,0,8,3,2021-01-01 01:00:00,4.0,23.0,28.0,8.0,7.0,3.3,92.0,NaN,NaN,NaN,NaN,NaN
1,1,8,3,2021-01-01 02:00:00,6.0,36.0,46.0,12.0,10.0,3.2,89.0,NaN,NaN,NaN,NaN,NaN
2,2,8,3,2021-01-01 03:00:00,2.0,19.0,22.0,5.0,4.0,3.8,83.0,NaN,NaN,NaN,NaN,NaN
3,3,8,3,2021-01-01 04:00:00,1.0,12.0,13.0,5.0,4.0,4.0,83.0,NaN,NaN,NaN,NaN,NaN
4,4,8,3,2021-01-01 05:00:00,1.0,12.0,13.0,1.0,1.0,3.9,81.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
338953,338953,60,8,2023-12-31 20:00:00,5.0,30.0,37.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
338954,338954,60,8,2023-12-31 21:00:00,6.0,35.0,44.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
338955,338955,60,8,2023-12-31 22:00:00,4.0,37.0,44.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
338956,338956,60,8,2023-12-31 23:00:00,2.0,20.0,23.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
338957,338957,60,8,2023-12-31 00:00:00,2.0,15.0,19.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Datos Trafico

## Ubicaciones

Datos de las ubicaciones, que he utilizado para eliminar las mediciones de trafico de los distritos que no estan en las mediciones de los contaminantes.

In [6]:
df_ubic = pd.read_csv("datos/ubicaciones_sensores_trafico.csv")

df_ubic

,Unnamed: 0,tipo_elem,distrito,id,cod_cent,nombre,utm_x,utm_y,longitud,latitud
0,0,URB,4.0,3840,01001,Jose Ortega y Gasset E-O - Pº Castellana-Serrano,441615.343346657,4475767.9421385,-3.6883232754856,40.4305018691825
1,1,URB,4.0,3841,01002,Jose Ortega y Gasset O-E - Serrano-Pº Castellana,441705.882339595,4475769.68733175,-3.68725610305613,40.4305239406404
2,2,URB,1.0,3842,01003,Pº Recoletos N-S - Almirante-Prim,441319.371258338,4474841.15423716,-3.6917268449043,40.4221320929972
3,3,URB,4.0,3843,01004,Pº Recoletos S-N - Pl. Cibeles- Recoletos,441301.63298559,4474763.7275141,-3.69192878230734,40.4214333442836
4,4,URB,4.0,3844,01005,(AFOROS) Pº Castellana S-N - Eduardo Dato - P...,441605.765071902,4476132.13924728,-3.68846965033102,40.4337820578943
...,...,...,...,...,...,...,...,...,...,...
5423,5423,URB,16.0,11235,72406,Av. Secundino Zuazo - César Cort Boti-Gta. Jos...,448.388.147.010.537,448.286.747.130.414,-360.905.755.542.047,404.949.062.864.003
5424,5424,URB,16.0,11276,72407,Av. Manuel Fraga Iribarne (CARRIL BUS) - AV. M...,44.843.325.332.997,448.251.275.311.267,-360.849.642.913.409,404.917.136.031.255
5425,5425,URB,16.0,11277,72408,Av. Manuel Fraga Iribarne (CARRIL BUS) - Jordi...,448.436.665.701.945,448.282.732.568.793,-360.848.176.299.328,404.945.476.496.166
5426,5426,URB,16.0,11279,72409,Secundino Zuazo (CARRIL BUS) - Josefina Aldeco...,447.824.682.462.605,448.294.459.287.868,-361.571.283.696.763,404.955.658.049.048
5427,5427,URB,16.0,11278,72410,Secundino Zuazo (CARRIL BUS) - Fina de Calderó...,447.748.942.805.197,448.294.078.306.391,-361.660.626.563.366,40.495.526.719.101

## MEDICIONES

Tengo las mediciones de los distritos de las estaciones

In [7]:
df_traf = pd.read_csv("datos/trafico2021_2023.csv")

df_traf

           Unnamed: 0    id                fecha tipo_elem  intensidad error
0               11892  1009  2021-01-01 00:00:00       M30         180     N
1               11893  1009  2021-01-01 00:15:00       M30         108     N
2               11894  1009  2021-01-01 00:30:00       M30         108     N
3               11895  1009  2021-01-01 00:45:00       M30         672     N
4               11896  1009  2021-01-01 01:00:00       M30        1452     N
...               ...   ...                  ...       ...         ...   ...
276996270   424091712  4738  2023-12-31 22:45:00       URB          20     N
276996271   424091713  4738  2023-12-31 23:00:00       URB          30     N
276996272   424091714  4738  2023-12-31 23:15:00       URB          20     N
276996273   424091715  4738  2023-12-31 23:30:00       URB          22     N
276996274   424091716  4738  2023-12-31 23:45:00       URB          12     N

[276996275 rows x 6 columns]

# Proximos pasos

Eliminar los datos de las mediciones no validos

Añadir el distrito a las mediciones de trafico para realizar calculos sobre ellos

Crear un nuevo df en el que:
- A partir de las mediciones, juntar por distrito, por Fecha Hora y tipo elem para calcular el total del flujo de coches
  - Puede ser calcular tambien promedio de los coches que pasan por