# Calcular trafico por distrito

In [1]:
import pandas as pd

df = pd.read_csv("datos/trafico_calculado_intensidad_hora.csv")

df

,Unnamed: 0,id,tipo_elem,distrito,fecha,intensidad
0,0,1009,C30,9.0,2022-12-01 09:00:00,420
1,1,1009,C30,9.0,2022-12-01 10:00:00,1680
2,2,1009,C30,9.0,2022-12-01 11:00:00,1680
3,3,1009,C30,9.0,2022-12-01 12:00:00,1680
4,4,1009,C30,9.0,2022-12-01 13:00:00,1680
...,...,...,...,...,...,...
70777069,70777069,11283,URB,5.0,2023-11-30 19:00:00,702
70777070,70777070,11283,URB,5.0,2023-11-30 20:00:00,519
70777071,70777071,11283,URB,5.0,2023-11-30 21:00:00,227
70777072,70777072,11283,URB,5.0,2023-11-30 22:00:00,142
70777073,70777073,11283,URB,5.0,2023-11-30 23:00:00,93

## Hay que sumar el total de intensidad para cada hora y distrito

## Quedarse solo con urbano

In [2]:
df['tipo_elem'].value_counts()

tipo_elem
URB      63896055
M30       5989120
C30        888252
other        3647
Name: count, dtype: int64

In [3]:
df = df.loc[df['tipo_elem'] == 'URB']
df

,Unnamed: 0,id,tipo_elem,distrito,fecha,intensidad
977650,977650,3398,URB,5.0,2021-01-01 00:00:00,531
977651,977651,3398,URB,5.0,2021-01-01 01:00:00,1568
977652,977652,3398,URB,5.0,2021-01-01 02:00:00,207
977653,977653,3398,URB,5.0,2021-01-01 03:00:00,110
977654,977654,3398,URB,5.0,2021-01-01 04:00:00,60
...,...,...,...,...,...,...
70777069,70777069,11283,URB,5.0,2023-11-30 19:00:00,702
70777070,70777070,11283,URB,5.0,2023-11-30 20:00:00,519
70777071,70777071,11283,URB,5.0,2023-11-30 21:00:00,227
70777072,70777072,11283,URB,5.0,2023-11-30 22:00:00,142
70777073,70777073,11283,URB,5.0,2023-11-30 23:00:00,93

# Calculo

In [19]:
df_calculado = df.groupby(['distrito', 'fecha'])['intensidad'].sum().reset_index()

df_calculado

        distrito                fecha  intensidad
0            1.0  2021-11-19 14:00:00          30
1            1.0  2021-11-21 11:00:00         120
2            1.0  2021-11-21 12:00:00         930
3            1.0  2021-11-21 13:00:00        3126
4            1.0  2021-11-21 14:00:00        4391
...          ...                  ...         ...
383172      21.0  2023-12-31 19:00:00        1512
383173      21.0  2023-12-31 20:00:00        1455
383174      21.0  2023-12-31 21:00:00         879
383175      21.0  2023-12-31 22:00:00         416
383176      21.0  2023-12-31 23:00:00         213

[383177 rows x 3 columns]

In [20]:
df_calculado.to_csv('datos/trafico_calculado_por_distrito.csv', index=False)  # index=False para no incluir los índices como una columna adicional

## Purebas

In [17]:
df_red = df.head(10)
df_red['fecha'] = '2021-01-01 00:00:00'

df_red.at[977651, 'fecha'] = '2021-02-01 00:00:00'


df_red.at[977656, 'distrito'] = 6.0
df_red.at[977657, 'distrito'] = 6.0
df_red.at[977658, 'distrito'] = 6.0
df_red.at[977659, 'distrito'] = 6.0

df_red

/var/folders/p9/nnj0ywtx27b7m3kq95j5n8mm0000gn/T/ipykernel_11124/563765180.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_red['fecha'] = '2021-01-01 00:00:00'

        Unnamed: 0    id tipo_elem  distrito                fecha  intensidad
977650      977650  3398       URB       5.0  2021-01-01 00:00:00         531
977651      977651  3398       URB       5.0  2021-02-01 00:00:00        1568
977652      977652  3398       URB       5.0  2021-01-01 00:00:00         207
977653      977653  3398       URB       5.0  2021-01-01 00:00:00         110
977654      977654  3398       URB       5.0  2021-01-01 00:00:00          60
977655      977655  3398       URB       5.0  2021-01-01 00:00:00          30
977656      977656  3398       URB       6.0  2021-01-01 00:00:00         220
977657      977657  3398       URB       6.0  2021-01-01 00:00:00         160
977658      977658  3398       URB       6.0  2021-01-01 00:00:00         198
977659      977659  3398       URB       6.0  2021-01-01 00:00:00         177

In [18]:
import pandas as pd

df_nuevo = df_red.groupby(['distrito', 'fecha'])['intensidad'].sum().reset_index()

df_nuevo

   distrito                fecha  intensidad
0       5.0  2021-01-01 00:00:00         938
1       5.0  2021-02-01 00:00:00        1568
2       6.0  2021-01-01 00:00:00         755