# Obtener las ubicaciones de los sensores

In [1]:
import pandas as pd

df1 = pd.read_csv("datos/trafico/ubicaciones/pmed_ubicacion_01-2021.csv", sep=';')
df2 = pd.read_csv("datos/trafico/ubicaciones/pmed_ubicacion_03-2021.csv", sep=';')
df3 = pd.read_csv("datos/trafico/ubicaciones/pmed_ubicacion_03-2022.csv", sep=';')
df4 = pd.read_csv("datos/trafico/ubicaciones/pmed_ubicacion_03-2023.csv", sep=';')
df5 = pd.read_csv("datos/trafico/ubicaciones/pmed_ubicacion_06-2021.csv", sep=';')
df6 = pd.read_csv("datos/trafico/ubicaciones/pmed_ubicacion_06-2022.csv", sep=';')
df7 = pd.read_csv("datos/trafico/ubicaciones/pmed_ubicacion_06-2023.csv", sep=';')
df8 = pd.read_csv("datos/trafico/ubicaciones/pmed_ubicacion_09-2021.csv", sep=';')
df9 = pd.read_csv("datos/trafico/ubicaciones/pmed_ubicacion_09-2022.csv", sep=';')
df10 = pd.read_csv("datos/trafico/ubicaciones/pmed_ubicacion_09-2023.csv", sep=';')
df11 = pd.read_csv("datos/trafico/ubicaciones/pmed_ubicacion_12-2021.csv", sep=';')
df12 = pd.read_csv("datos/trafico/ubicaciones/pmed_ubicacion_12-2022.csv", sep=';')
df13 = pd.read_csv("datos/trafico/ubicaciones/pmed_ubicacion_12-2023.csv", sep=';')

In [2]:
print(list(df1.columns) == list(df2.columns) == list(df3.columns) == list(df4.columns) == list(df5.columns) == list(df6.columns) == list(df7.columns) == list(df8.columns) == list(df9.columns) == list(df10.columns) == list(df11.columns) == list(df12.columns )== list(df13.columns))

True

In [3]:
dfs = [df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12, df13]

df_final = pd.concat(dfs).drop_duplicates()

df_final = df_final.reset_index(drop=True)

df_final

,tipo_elem,distrito,id,cod_cent,nombre,utm_x,utm_y,longitud,latitud
0,URB,4.0,3840,01001,Jose Ortega y Gasset E-O - Pº Castellana-Serrano,441615.343347,4475767.942138,-3.688323,40.430502
1,URB,4.0,3841,01002,Jose Ortega y Gasset O-E - Serrano-Pº Castellana,441705.88234,4475769.687332,-3.687256,40.430524
2,URB,1.0,3842,01003,Pº Recoletos N-S - Almirante-Prim,441319.371258,4474841.154237,-3.691727,40.422132
3,URB,4.0,3843,01004,Pº Recoletos S-N - Pl. Cibeles- Recoletos,441301.632986,4474763.727514,-3.691929,40.421433
4,URB,4.0,3844,01005,(AFOROS) Pº Castellana S-N - Eduardo Dato - P...,441605.765072,4476132.139247,-3.68847,40.433782
...,...,...,...,...,...,...,...,...,...
11356,M30,16.0,6809,PM43201,PM43201,444.065.316.509.731,448.158.574.831.358,-365.995.390.537.605,404.830.798.779.355
11357,M30,16.0,6810,PM43202,PM43202,444.067.760.452.618,448.159.438.477.012,-365.992.583.390.915,404.831.578.436.592
11358,M30,16.0,6933,PM43221,PM43221,443.003.125.903.452,448.170.905.942.662,-367.249.659.818.133,404.841.184.798.411
11359,M30,16.0,7129,PM43222,PM43222,443.002.925.186.071,448.171.603.668.391,-367.249.959.357.655,404.841.813.201.606
11360,M30,16.0,7015,PM43223,PM43223,443.019.864.262.447,448.180.705.761.374,-367.230.792.648.148,404.850.024.380.449

In [4]:
columnas_clave = ['tipo_elem', 'distrito', 'id', 'cod_cent']

df_final2 = pd.concat(dfs)
df_final2 = df_final2.drop_duplicates(subset=columnas_clave)

df_final2 = df_final2.reset_index(drop=True)

df_final2

,tipo_elem,distrito,id,cod_cent,nombre,utm_x,utm_y,longitud,latitud
0,URB,4.0,3840,01001,Jose Ortega y Gasset E-O - Pº Castellana-Serrano,441615.343347,4475767.942138,-3.688323,40.430502
1,URB,4.0,3841,01002,Jose Ortega y Gasset O-E - Serrano-Pº Castellana,441705.88234,4475769.687332,-3.687256,40.430524
2,URB,1.0,3842,01003,Pº Recoletos N-S - Almirante-Prim,441319.371258,4474841.154237,-3.691727,40.422132
3,URB,4.0,3843,01004,Pº Recoletos S-N - Pl. Cibeles- Recoletos,441301.632986,4474763.727514,-3.691929,40.421433
4,URB,4.0,3844,01005,(AFOROS) Pº Castellana S-N - Eduardo Dato - P...,441605.765072,4476132.139247,-3.68847,40.433782
...,...,...,...,...,...,...,...,...,...
5423,URB,16.0,11235,72406,Av. Secundino Zuazo - César Cort Boti-Gta. Jos...,448.388.147.010.537,448.286.747.130.414,-360.905.755.542.047,404.949.062.864.003
5424,URB,16.0,11276,72407,Av. Manuel Fraga Iribarne (CARRIL BUS) - AV. M...,44.843.325.332.997,448.251.275.311.267,-360.849.642.913.409,404.917.136.031.255
5425,URB,16.0,11277,72408,Av. Manuel Fraga Iribarne (CARRIL BUS) - Jordi...,448.436.665.701.945,448.282.732.568.793,-360.848.176.299.328,404.945.476.496.166
5426,URB,16.0,11279,72409,Secundino Zuazo (CARRIL BUS) - Josefina Aldeco...,447.824.682.462.605,448.294.459.287.868,-361.571.283.696.763,404.955.658.049.048
5427,URB,16.0,11278,72410,Secundino Zuazo (CARRIL BUS) - Fina de Calderó...,447.748.942.805.197,448.294.078.306.391,-361.660.626.563.366,40.495.526.719.101

In [5]:
for df in dfs:
    print(len(df))

4370
4476
4609
4718
4492
4622
4746
4527
4663
4824
4571
4690
4894

In [6]:
df_final2.to_csv("datos/ubicaciones_sensores_trafico.csv")