# Ver que puntos de medicion tienen mas datos.

In [1]:
import pandas as pd

df = pd.read_csv("datos/cont_meteo_juntos_2021_2024.csv")

df.drop(columns='Unnamed: 0', inplace=True)

In [2]:
import pandas as pd

columnas = ['NO', 'NO2', 'NOx', 'BEN', 'CO', 'EBE', 'O3', 'PM10', 'PM2_5', 'SO2', 'TOL']  # Puedes agregar más columnas aquí si es necesario

valores_nan_por_estacion = df.groupby('ESTACION')[columnas].apply(lambda x: x.isna().sum())

total_por_estacion = df['ESTACION'].value_counts().reset_index()
total_por_estacion.columns = ['ESTACION', 'TOTAL_MUESTRAS']

valores_nan_por_estacion = pd.merge(valores_nan_por_estacion, total_por_estacion, on='ESTACION')

for columna in columnas:
    valores_nan_por_estacion[columna] = (valores_nan_por_estacion[columna] / valores_nan_por_estacion['TOTAL_MUESTRAS']) * 100

valores_nan_por_estacion = valores_nan_por_estacion[['ESTACION'] + columnas]

valores_nan_por_estacion = valores_nan_por_estacion.sort_values(by='ESTACION').reset_index(drop=True)

valores_nan_por_estacion = valores_nan_por_estacion.round(2)

valores_nan_por_estacion

,ESTACION,NO,NO2,NOx,BEN,CO,EBE,O3,PM10,PM2_5,SO2,TOL
0,4,8.15,7.71,9.00,100.00,7.14,100.00,100.00,100.00,100.00,7.22,100.00
1,8,5.38,5.30,5.22,8.01,4.81,7.91,5.95,11.71,11.49,6.12,7.31
2,11,3.83,4.05,4.49,6.88,100.00,6.44,100.00,100.00,100.00,100.00,8.69
3,16,8.76,3.46,2.69,100.00,100.00,100.00,5.86,100.00,100.00,100.00,100.00
4,17,4.09,3.85,5.79,100.00,100.00,100.00,9.47,100.00,100.00,100.00,100.00
5,18,4.59,5.50,5.23,9.48,71.02,8.86,5.14,10.67,100.00,88.25,9.50
6,24,5.86,6.50,7.74,7.71,100.00,5.44,9.09,6.65,4.76,100.00,10.01
7,27,4.02,4.38,4.09,100.00,100.00,100.00,4.28,100.00,100.00,100.00,100.00
8,35,9.71,9.73,6.99,100.00,7.85,100.00,7.23,100.00,100.00,7.39,100.00
9,36,5.00,3.49,4.46,100.00,100.00,100.00,100.00,4.62,100.00,12.03,100.00
10,38,4.72,6.28,4.46,5.85,100.00,7.15,100.00,10.66,10.78,100.00,6.18
11,39,3.62,3.80,5.35,100.00,100.00,100.00,4.40,100.00,100.00,100.00,100.00
12,40,3.30,3.35,5.12,100.00,100.00,100.00,100.00,5.63,100.00,100.00,100.00
13,47,3.98,4.26,2.96,100.00,100.00,100.00,100.00,6.13,6.88,100.00,100.00
14,48,2.83,2.10,2.95,100.00,100.00,100.00,100.00,6.66,5.72,100.00,100.00
15,49,2.73,2.95,2.33,100.00,100.00,100.00,2.51,100.00,100.00,100.00,100.00
16,50,3.80,4.38,3.71,100.00,100.00,100.00,100.00,6.24,5.99,100.00,100.00
17,54,2.52,2.52,3.78,100.00,100.00,100.00,5.96,100.00,100.00,100.00,100.00
18,55,4.52,4.11,4.95,13.00,100.00,9.65,100.00,8.17,100.00,100.00,11.06
19,56,6.55,5.24,3.68,100.00,8.07,100.00,87.12,4.24,4.46,100.00,100.00
20,57,4.58,3.90,2.83,100.00,100.00,100.00,100.00,4.73,30.46,68.43,100.00
21,58,2.37,2.51,2.34,100.00,100.00,100.00,3.39,100.00,100.00,100.00,100.00
22,59,3.92,4.69,3.72,100.00,100.00,100.00,3.55,100.00,100.00,100.00,100.00
23,60,4.44,5.45,5.23,100.00,100.00,100.00,5.16,5.92,100.00,100.00,100.00

In [3]:
'''
valores_nan_por_estacion = df.groupby('ESTACION')['PM10'].apply(lambda x: x.isna().sum())

total_por_estacion = df['ESTACION'].value_counts()

porcentaje_nan_por_estacion = (valores_nan_por_estacion / total_por_estacion) * 100

porcentaje_nan_por_estacion.sort_values()
'''

"\nvalores_nan_por_estacion = df.groupby('ESTACION')['PM10'].apply(lambda x: x.isna().sum())\n\ntotal_por_estacion = df['ESTACION'].value_counts()\n\nporcentaje_nan_por_estacion = (valores_nan_por_estacion / total_por_estacion) * 100\n\nporcentaje_nan_por_estacion.sort_values()\n"

## Saber a que distrito pertenece cada estación

### Con saber a que distrito pertenece puedo filtrar los datos de trefico

In [4]:
df1 = pd.read_csv("datos/contaminacion/anio21/ene_mo21.csv", sep=';')
df2 = pd.read_csv("datos/contaminacion/anio21/feb_mo21.csv", sep=';')
df3 = pd.read_csv("datos/contaminacion/anio21/mar_mo21.csv", sep=';')
df4 = pd.read_csv("datos/contaminacion/anio21/abr_mo21.csv", sep=';')
df5 = pd.read_csv("datos/contaminacion/anio21/may_mo21.csv", sep=';')
df6 = pd.read_csv("datos/contaminacion/anio21/jun_mo21.csv", sep=';')
df7 = pd.read_csv("datos/contaminacion/anio21/jul_mo21.csv", sep=';')
df8 = pd.read_csv("datos/contaminacion/anio21/ago_mo21.csv", sep=';')
df9 = pd.read_csv("datos/contaminacion/anio21/sep_mo21.csv", sep=';')
df10 = pd.read_csv("datos/contaminacion/anio21/oct_mo21.csv", sep=';')
df11 = pd.read_csv("datos/contaminacion/anio21/nov_mo21.csv", sep=';')
df12 = pd.read_csv("datos/contaminacion/anio21/dic_mo21.csv", sep=';')

df2021 = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12], ignore_index=True)

del [df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12]

df1 = pd.read_csv("datos/contaminacion/anio22/ene_mo22.csv", sep=';')
df2 = pd.read_csv("datos/contaminacion/anio22/feb_mo22.csv", sep=';')
df3 = pd.read_csv("datos/contaminacion/anio22/mar_mo22.csv", sep=';')
df4 = pd.read_csv("datos/contaminacion/anio22/abr_mo22.csv", sep=';')
df5 = pd.read_csv("datos/contaminacion/anio22/may_mo22.csv", sep=';')
df6 = pd.read_csv("datos/contaminacion/anio22/jun_mo22.csv", sep=';')
df7 = pd.read_csv("datos/contaminacion/anio22/jul_mo22.csv", sep=';')
df8 = pd.read_csv("datos/contaminacion/anio22/ago_mo22.csv", sep=';')
df9 = pd.read_csv("datos/contaminacion/anio22/sep_mo22.csv", sep=';')
df10 = pd.read_csv("datos/contaminacion/anio22/oct_mo22.csv", sep=';')
df11 = pd.read_csv("datos/contaminacion/anio22/nov_mo22.csv", sep=';')
df12 = pd.read_csv("datos/contaminacion/anio22/dic_mo22.csv", sep=';')

df2022 = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12], ignore_index=True)

del [df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12]

df1 = pd.read_csv("datos/contaminacion/anio23/ene_mo23.csv", sep=';')
df2 = pd.read_csv("datos/contaminacion/anio23/feb_mo23.csv", sep=';')
df3 = pd.read_csv("datos/contaminacion/anio23/mar_mo23.csv", sep=';')
df4 = pd.read_csv("datos/contaminacion/anio23/abr_mo23.csv", sep=';')
df5 = pd.read_csv("datos/contaminacion/anio23/may_mo23.csv", sep=';')
df6 = pd.read_csv("datos/contaminacion/anio23/jun_mo23.csv", sep=';')
df7 = pd.read_csv("datos/contaminacion/anio23/jul_mo23.csv", sep=';')
df8 = pd.read_csv("datos/contaminacion/anio23/ago_mo23.csv", sep=';')
df9 = pd.read_csv("datos/contaminacion/anio23/sep_mo23.csv", sep=';')
df10 = pd.read_csv("datos/contaminacion/anio23/oct_mo23.csv", sep=';')
df11 = pd.read_csv("datos/contaminacion/anio23/nov_mo23.csv", sep=';')
df12 = pd.read_csv("datos/contaminacion/anio23/dic_mo23.csv", sep=';')

df2023 = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12], ignore_index=True)

del [df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12]

df = pd.concat([df2021, df2022, df2023])

del [df2021, df2022, df2023]

df['FECHA'] = df['DIA'].astype(str) + '/' + df['MES'].astype(str) + '/' + df['ANO'].astype(str)

df = df.drop(columns=['ANO', 'MES', 'DIA'])

df['FECHA'] = pd.to_datetime(df['FECHA'], format='%d/%m/%Y')

mapeo = {1: 'SO2',
         6: 'CO',
         7: 'NO',
         8: 'NO2',
         9: 'PM2_5',
         10: 'PM10',
         12: 'NOx',
         14: 'O3',
         20: 'TOL',
         30: 'BEN',
         35: 'EBE',
         37: 'MXY',
         38: 'PXY',
         39: 'OXY',
         42: 'TCH',
         43: 'CH4',
         44: 'NMHC'}

df['MAGNITUD'] = df['MAGNITUD'].map(mapeo)

df = df.drop(columns=['PROVINCIA', 'MUNICIPIO'])

import numpy as np

def eliminar_contenido(df, v_column, h_column):
    # Obtener los índices donde v es N
    indices_v_F = df.loc[df[v_column] == 'N'].index
    # Eliminar el valor de las celdas
    df.loc[indices_v_F, h_column] = np.nan
    return df

df = eliminar_contenido(df, 'V01', 'H01')
df = eliminar_contenido(df, 'V02', 'H02')
df = eliminar_contenido(df, 'V03', 'H03')
df = eliminar_contenido(df, 'V04', 'H04')
df = eliminar_contenido(df, 'V05', 'H05')
df = eliminar_contenido(df, 'V06', 'H06')
df = eliminar_contenido(df, 'V07', 'H07')
df = eliminar_contenido(df, 'V08', 'H08')
df = eliminar_contenido(df, 'V09', 'H09')
df = eliminar_contenido(df, 'V10', 'H10')
df = eliminar_contenido(df, 'V11', 'H11')
df = eliminar_contenido(df, 'V12', 'H12')
df = eliminar_contenido(df, 'V13', 'H13')
df = eliminar_contenido(df, 'V14', 'H14')
df = eliminar_contenido(df, 'V15', 'H15')
df = eliminar_contenido(df, 'V16', 'H16')
df = eliminar_contenido(df, 'V17', 'H17')
df = eliminar_contenido(df, 'V18', 'H18')
df = eliminar_contenido(df, 'V19', 'H19')
df = eliminar_contenido(df, 'V20', 'H20')
df = eliminar_contenido(df, 'V21', 'H21')
df = eliminar_contenido(df, 'V22', 'H22')
df = eliminar_contenido(df, 'V23', 'H23')
df = eliminar_contenido(df, 'V24', 'H24')

df = df.drop(columns=['V01', 'V02', 'V03', 'V04', 'V05', 'V06', 'V02', 'V08', 'V09', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24'])

df = pd.melt(df, 
                id_vars=['ESTACION', 'MAGNITUD', 'PUNTO_MUESTREO', 'FECHA'], 
                value_vars=['H01', 'H02', 'H03', 'H04', 'H05', 'H06', 'H07', 'H08', 'H09', 'H10', 'H11', 'H12', 'H13', 'H14', 'H15', 'H16', 'H17', 'H18', 'H19', 'H20', 'H21', 'H22', 'H23', 'H24'], 
                var_name='HORA', 
                value_name='VALOR')

df

         ESTACION MAGNITUD PUNTO_MUESTREO      FECHA HORA  VALOR
0               4      SO2  28079004_1_38 2021-01-01  H01    6.0
1               4      SO2  28079004_1_38 2021-01-02  H01    4.0
2               4      SO2  28079004_1_38 2021-01-03  H01    6.0
3               4      SO2  28079004_1_38 2021-01-04  H01    5.0
4               4      SO2  28079004_1_38 2021-01-05  H01    4.0
...           ...      ...            ...        ...  ...    ...
3428011        60       O3  28079060_14_6 2023-12-27  H24   18.0
3428012        60       O3  28079060_14_6 2023-12-28  H24   25.0
3428013        60       O3  28079060_14_6 2023-12-29  H24   15.0
3428014        60       O3  28079060_14_6 2023-12-30  H24   20.0
3428015        60       O3  28079060_14_6 2023-12-31  H24   54.0

[3428016 rows x 6 columns]

A partir de aqui hay que ver el punto muestreo, a que distrito pertenece

Voy a agrupar por magnitud y punto muestreo para ver en cada punto lo que se mide

In [5]:
grupos = df.groupby('MAGNITUD')['PUNTO_MUESTREO'].unique()

combinaciones_presentes = [(magnitudes, punto) for punto, magnitudes in grupos.items()]

print(combinaciones_presentes)

[(array(['28079008_30_59', '28079011_30_59', '28079018_30_59',
       '28079024_30_59', '28079038_30_59', '28079055_30_59'], dtype=object), 'BEN'), (array(['28079008_43_2', '28079024_43_2', '28079055_43_2'], dtype=object), 'CH4'), (array(['28079004_6_48', '28079008_6_48', '28079016_6_48', '28079018_6_48',
       '28079024_6_48', '28079035_6_48', '28079036_6_48', '28079039_6_48',
       '28079056_6_48', '28079057_6_48'], dtype=object), 'CO'), (array(['28079008_35_59', '28079011_35_59', '28079018_35_59',
       '28079024_35_59', '28079038_35_59', '28079055_35_59'], dtype=object), 'EBE'), (array(['28079008_44_2', '28079024_44_2', '28079055_44_2'], dtype=object), 'NMHC'), (array(['28079004_7_8', '28079008_7_8', '28079011_7_8', '28079016_7_8',
       '28079017_7_8', '28079018_7_8', '28079024_7_8', '28079027_7_8',
       '28079035_7_8', '28079036_7_8', '28079038_7_8', '28079039_7_8',
       '28079040_7_8', '28079047_7_8', '28079048_7_8', '28079049_7_8',
       '28079050_7_8', '28079054_7_8', '28079055_7_8', '28079056_7_8',
       '28079057_7_8', '28079058_7_8', '28079059_7_8', '28079060_7_8'],
      dtype=object), 'NO'), (array(['28079004_8_8', '28079008_8_8', '28079011_8_8', '28079016_8_8',
       '28079017_8_8', '28079018_8_8', '28079024_8_8', '28079027_8_8',
       '28079035_8_8', '28079036_8_8', '28079038_8_8', '28079039_8_8',
       '28079040_8_8', '28079047_8_8', '28079048_8_8', '28079049_8_8',
       '28079050_8_8', '28079054_8_8', '28079055_8_8', '28079056_8_8',
       '28079057_8_8', '28079058_8_8', '28079059_8_8', '28079060_8_8'],
      dtype=object), 'NO2'), (array(['28079004_12_8', '28079008_12_8', '28079011_12_8', '28079016_12_8',
       '28079017_12_8', '28079018_12_8', '28079024_12_8', '28079027_12_8',
       '28079035_12_8', '28079036_12_8', '28079038_12_8', '28079039_12_8',
       '28079040_12_8', '28079047_12_8', '28079048_12_8', '28079049_12_8',
       '28079050_12_8', '28079054_12_8', '28079055_12_8', '28079056_12_8',
       '28079057_12_8', '28079058_12_8', '28079059_12_8', '28079060_12_8'],
      dtype=object), 'NOx'), (array(['28079008_14_6', '28079016_14_6', '28079017_14_6', '28079018_14_6',
       '28079024_14_6', '28079027_14_6', '28079035_14_6', '28079039_14_6',
       '28079049_14_6', '28079054_14_6', '28079056_14_6', '28079058_14_6',
       '28079059_14_6', '28079060_14_6'], dtype=object), 'O3'), (array(['28079008_10_47', '28079018_10_47', '28079024_10_47',
       '28079036_10_47', '28079038_10_47', '28079040_10_47',
       '28079047_10_47', '28079048_10_47', '28079050_10_47',
       '28079055_10_47', '28079056_10_47', '28079057_10_47',
       '28079060_10_47'], dtype=object), 'PM10'), (array(['28079008_9_47', '28079024_9_47', '28079038_9_47', '28079047_9_47',
       '28079048_9_47', '28079050_9_47', '28079056_9_47', '28079057_9_47'],
      dtype=object), 'PM2_5'), (array(['28079004_1_38', '28079008_1_38', '28079017_1_38', '28079018_1_38',
       '28079024_1_38', '28079035_1_38', '28079036_1_38', '28079038_1_38',
       '28079040_1_38', '28079057_1_38'], dtype=object), 'SO2'), (array(['28079008_42_2', '28079024_42_2', '28079055_42_2'], dtype=object), 'TCH'), (array(['28079008_20_59', '28079011_20_59', '28079018_20_59',
       '28079024_20_59', '28079038_20_59', '28079055_20_59'], dtype=object), 'TOL')]

Los puntos no tienen mucha informacion:

> El campo punto de muestreo incluye el código de la estación completo (provincia, municipio y estación) más la magnitud y la técnica de muestreo.

Por lo que la información presente es la misma que en el campo ESTACIÓN.

SOLUCION: Poner el distrito manualmente segun las direcciones presentes en el pdf explicativo.