#  DATOS DE TRAFICO 

- JUNTAR POR AÑOS 
- ELIMINAR COLUMNAS QUE NO SIRVEN

In [25]:
import pandas as pd

df_datos = pd.read_csv("datos/CONT_METEO_REDUCIDO_2021_2024.csv")

df_datos.drop(columns='Unnamed: 0', inplace=True)

df_datos

,ESTACION,DISTRITO,FECHA_HORA,NO,NO2,NOx,PM10,PM2_5,TEMP,HUM_REL,PRECIPITACION,PRES_BARIOMETRICA,RAD_SOL,DIR_VIENT,VEL_VIENT
0,8,3,2021-01-01 01:00:00,4.0,23.0,28.0,8.0,7.0,3.3,92.0,NaN,NaN,NaN,NaN,NaN
1,8,3,2021-01-01 02:00:00,6.0,36.0,46.0,12.0,10.0,3.2,89.0,NaN,NaN,NaN,NaN,NaN
2,8,3,2021-01-01 03:00:00,2.0,19.0,22.0,5.0,4.0,3.8,83.0,NaN,NaN,NaN,NaN,NaN
3,8,3,2021-01-01 04:00:00,1.0,12.0,13.0,5.0,4.0,4.0,83.0,NaN,NaN,NaN,NaN,NaN
4,8,3,2021-01-01 05:00:00,1.0,12.0,13.0,1.0,1.0,3.9,81.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
338953,60,8,2023-12-31 20:00:00,5.0,30.0,37.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
338954,60,8,2023-12-31 21:00:00,6.0,35.0,44.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
338955,60,8,2023-12-31 22:00:00,4.0,37.0,44.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
338956,60,8,2023-12-31 23:00:00,2.0,20.0,23.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
338957,60,8,2023-12-31 00:00:00,2.0,15.0,19.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
estaciones_lista = df_datos['ESTACION'].unique()
estaciones_lista.sort()
estaciones_lista

array([ 8, 18, 24, 36, 38, 40, 47, 48, 50, 55, 56, 57, 60])

In [27]:
distritos_lista = df_datos['DISTRITO'].unique()
distritos_lista.sort()
distritos_lista

array([ 2,  3,  4,  5,  6,  8,  9, 11, 12, 14, 16, 18, 21])

## DE LOS DATOS DE TRAFICO ELIMINO LAS COLUMNAS OCUPACION CARGA VMED Y PERIODO_INTEGRACION

# DATOS TRAFICO 2021

In [28]:
df1 = pd.read_csv("datos/trafico/mediciones/2021/01-2021.csv", sep=';')
df2 = pd.read_csv("datos/trafico/mediciones/2021/02-2021.csv", sep=';')
df3 = pd.read_csv("datos/trafico/mediciones/2021/03-2021.csv", sep=';')
df4 = pd.read_csv("datos/trafico/mediciones/2021/04-2021.csv", sep=';')
df5 = pd.read_csv("datos/trafico/mediciones/2021/05-2021.csv", sep=';')
df6 = pd.read_csv("datos/trafico/mediciones/2021/06-2021.csv", sep=';')
df7 = pd.read_csv("datos/trafico/mediciones/2021/07-2021.csv", sep=';')
df8 = pd.read_csv("datos/trafico/mediciones/2021/08-2021.csv", sep=';')
df9 = pd.read_csv("datos/trafico/mediciones/2021/09-2021.csv", sep=';')
df10 = pd.read_csv("datos/trafico/mediciones/2021/10-2021.csv", sep=';')
df11 = pd.read_csv("datos/trafico/mediciones/2021/11-2021.csv", sep=';')
df12 = pd.read_csv("datos/trafico/mediciones/2021/12-2021.csv", sep=';')

print(list(df1.columns) == list(df2.columns) == list(df3.columns) == list(df4.columns) == list(df5.columns) == list(df6.columns) == list(df7.columns) == list(df8.columns) == list(df9.columns) == list(df10.columns) == list(df11.columns) == list(df12.columns ))

dfs = [df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12]

columnas_a_eliminar = ['ocupacion', 'carga', 'vmed', 'periodo_integracion']

for df in dfs:
    df.drop(columns=columnas_a_eliminar, inplace=True)

df_trafico_2021 = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12], ignore_index=True)

df_trafico_2021 = df_trafico_2021.reset_index(drop=True)

del [df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12]

df_trafico_2021

True

              id                fecha tipo_elem  intensidad error
0           1001  2021-01-01 00:00:00       M30         144     N
1           1001  2021-01-01 00:15:00       M30          84     N
2           1001  2021-01-01 00:30:00       M30         108     N
3           1001  2021-01-01 00:45:00       M30         792     N
4           1001  2021-01-01 01:00:00       M30        1704     N
...          ...                  ...       ...         ...   ...
139723574  10920  2021-12-31 22:45:00       URB          46     N
139723575  10920  2021-12-31 23:00:00       URB          38     N
139723576  10920  2021-12-31 23:15:00       URB          42     N
139723577  10920  2021-12-31 23:30:00       URB          36     N
139723578  10920  2021-12-31 23:45:00       URB          12     N

[139723579 rows x 5 columns]

# DATOS TRAFICO 2022

In [29]:
df1 = pd.read_csv("datos/trafico/mediciones/2022/01-2022.csv", sep=';')
df2 = pd.read_csv("datos/trafico/mediciones/2022/02-2022.csv", sep=';')
df3 = pd.read_csv("datos/trafico/mediciones/2022/03-2022.csv", sep=';')
df4 = pd.read_csv("datos/trafico/mediciones/2022/04-2022.csv", sep=';')
df5 = pd.read_csv("datos/trafico/mediciones/2022/05-2022.csv", sep=';')
df6 = pd.read_csv("datos/trafico/mediciones/2022/06-2022.csv", sep=';')
df7 = pd.read_csv("datos/trafico/mediciones/2022/07-2022.csv", sep=';')
df8 = pd.read_csv("datos/trafico/mediciones/2022/08-2022.csv", sep=';')
df9 = pd.read_csv("datos/trafico/mediciones/2022/09-2022.csv", sep=';')
df10 = pd.read_csv("datos/trafico/mediciones/2022/10-2022.csv", sep=';')
df11 = pd.read_csv("datos/trafico/mediciones/2022/11-2022.csv", sep=';')
df12 = pd.read_csv("datos/trafico/mediciones/2022/12-2022.csv", sep=';')

print(list(df1.columns) == list(df2.columns) == list(df3.columns) == list(df4.columns) == list(df5.columns) == list(df6.columns) == list(df7.columns) == list(df8.columns) == list(df9.columns) == list(df10.columns) == list(df11.columns) == list(df12.columns ))

dfs = [df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12]

columnas_a_eliminar = ['ocupacion', 'carga', 'vmed', 'periodo_integracion']

for df in dfs:
    df.drop(columns=columnas_a_eliminar, inplace=True)

df_trafico_2022 = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12], ignore_index=True)

df_trafico_2022 = df_trafico_2022.reset_index(drop=True)

del [df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12]

df_trafico_2022

True

               id                fecha tipo_elem  intensidad error
0            1001  2022-01-01 00:00:00       M30         408     N
1            1001  2022-01-01 00:15:00       M30         156     N
2            1001  2022-01-01 00:30:00       M30         192     N
3            1001  2022-01-01 00:45:00       M30         600     N
4            1001  2022-01-01 01:00:00       M30        1065     N
...           ...                  ...       ...         ...   ...
142255076   11058  2022-12-31 23:00:00       URB          66     N
142255077   11058  2022-12-31 23:15:00       URB          37     N
142255078   11058  2022-12-31 23:30:00       URB          42     N
142255079   11058  2022-12-31 23:45:00       URB          26     N
142255080  479309  2022-12-11 04:15:00       URB           0     N

[142255081 rows x 5 columns]

# DATOS TRAFICO 2023

In [30]:
df1 = pd.read_csv("datos/trafico/mediciones/2023/01-2023.csv", sep=';')
df2 = pd.read_csv("datos/trafico/mediciones/2023/02-2023.csv", sep=';')
df3 = pd.read_csv("datos/trafico/mediciones/2023/03-2023.csv", sep=';')
df4 = pd.read_csv("datos/trafico/mediciones/2023/04-2023.csv", sep=';')
df5 = pd.read_csv("datos/trafico/mediciones/2023/05-2023.csv", sep=';')
df6 = pd.read_csv("datos/trafico/mediciones/2023/06-2023.csv", sep=';')
df7 = pd.read_csv("datos/trafico/mediciones/2023/07-2023.csv", sep=';')
df8 = pd.read_csv("datos/trafico/mediciones/2023/08-2023.csv", sep=';')
df9 = pd.read_csv("datos/trafico/mediciones/2023/09-2023.csv", sep=';')
df10 = pd.read_csv("datos/trafico/mediciones/2023/10-2023.csv", sep=';')
df11 = pd.read_csv("datos/trafico/mediciones/2023/11-2023.csv", sep=';')
df12 = pd.read_csv("datos/trafico/mediciones/2023/12-2023.csv", sep=';')

print(list(df1.columns) == list(df2.columns) == list(df3.columns) == list(df4.columns) == list(df5.columns) == list(df6.columns) == list(df7.columns) == list(df8.columns) == list(df9.columns) == list(df10.columns) == list(df11.columns) == list(df12.columns ))

dfs = [df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12]

columnas_a_eliminar = ['ocupacion', 'carga', 'vmed', 'periodo_integracion']

for df in dfs:
    df.drop(columns=columnas_a_eliminar, inplace=True)

df_trafico_2023 = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12], ignore_index=True)

df_trafico_2023 = df_trafico_2023.reset_index(drop=True)

del [df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12]

df_trafico_2023

True

             id                fecha tipo_elem  intensidad error
0          1001  2023-01-01 00:00:00       C30           0     N
1          1001  2023-01-01 00:15:00       C30           0     N
2          1001  2023-01-01 00:30:00       C30         180     N
3          1001  2023-01-01 00:45:00       C30         180     N
4          1001  2023-01-01 01:00:00       C30         180     N
...         ...                  ...       ...         ...   ...
142128614  4744  2023-12-08 05:15:00       URB          51     N
142128615  4744  2023-12-08 05:30:00       URB          64     N
142128616  4744  2023-12-08 05:45:00       URB          48     N
142128617  4744  2023-12-08 06:00:00       URB          60     N
142128618  4744  2023-12-08 06:15:00       URB          48     N

[142128619 rows x 5 columns]

# JUNTAR LOS DATOS

In [31]:
print(list(df_trafico_2021.columns) == list(df_trafico_2022.columns) == list(df_trafico_2023.columns))

True

In [32]:
df = pd.concat([df_trafico_2021, df_trafico_2022, df_trafico_2023])

del [df_trafico_2021, df_trafico_2022, df_trafico_2023]

In [33]:
df.to_csv("datos/trafico2021_2023.csv")